log:
  MaxSize: 100
  MaxAge: 30
  level: debug
  mode: staging      #dev|staging


private-chat:
  host: 127.0.0.1
  port: 8080
  redis:
    host:
    port:
  mysql:
    charset: utf8mb4
    host: 127.0.0.1:3306
    user: root
    password: 123456
    name: private-chat
    pool:
      max: 20
      min: 5

  prod:
    host:
    port:
    mysql:
      charset: utf8mb4
      host: 127.0.0.1:3306
      user: root
      password: 123456
      name: private-chat
      pool:
        max: 20
        min: 5


