log:
  path: ./report/
  MaxSize: 100
  MaxAge: 30
  level: debug
  mode: staging      #dev|staging

secret: 1231das3fdsf-23123
api:
  uv: 8459cb92691474b6a92eeddb3cbe7be2
  baidu: kYermFA2vFEkaf6CPgFoAv2ml5cFe0t2
  alibb: 2e018efa22785ccffe6a24de60a8fc05

#阿里巴巴云存储
alibaba:
  accessKey: TFRBSTV0QnFCeXp5M25idG82Q3F3RTZl
  accessKeySecret: Qgb10mwFeGYJB2LWN6KvfDNuNd9GQo
  cors:
    bucket: chat-image-2021-12-03
    Endpoint: oss-cn-beijing.aliyuncs.com
    chatImagePortraitDir: userPortrait/
    chatImageSisterDir: sister/


#项目环境配置
private-chat:
  host: 127.0.0.1
  port: 8080
  redis:
    host:
    port:
  mysql:
    charset: utf8mb4
    host: 127.0.0.1:3306
    user: root
    password: 123456
    name: private-chat
    pool:
      max: 20
      min: 5

  prod:         #生产配置
    host:
    port:
    mysql:
      charset: utf8mb4
      host: 127.0.0.1:3306
      user: root
      password: 123456
      name: private-chat
      pool:
        max: 20
        min: 5

redis:
  host: 127.0.0.1:6379
  auth: 12345
  db: 0
  pool:
    max: 20
    min: 3
  taskBrokerDB: 10
  taskResultBackendDB: 11
  latexTaskBrokerDB: 8
  latexTaskResultBackendDB: 9


smtp:
  from: 1500676800@qq.com
  qq:
    host: smtp.qq.com
    port: 25             # SSL协议端口：465/994
    username: 1500676800
    password: oongfnnuwjnfhfgi          #这里是授权码

  wy:
    host: smtp.163.com
    port: 25
    username:
    password: